kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    name: dev

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-pods
  namespace: dev
subjects:
- kind: User
  name: user-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: creator
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: creator
rules:
- apiGroups: [""]
  resources: ["pods, deployments, services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]

---
kind: Pod
apiVersion: v1
metadata:
  name: hello-world
  namespace: dev
  labels:
    app: sample-java-app
spec:
  containers:
    - name: hello-world
      image: phaneindra/sample-java-app:latest

---

kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  namespace: dev
  labels:
   app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"

---

kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  namespace: dev
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"

---

kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: dev
spec:
  selector:
    app: sample-java-app
  ports:
    - port: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
  namespace: dev
spec:
  selector:
    app: banana
  ports:
    - port: 5678

---

apiVersion: v1
kind: Service
metadata:
  name: apple-service
  namespace: dev
spec:
  selector:
    app: apple
  ports:
  - port: 5678
