kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-pods
  namespace: dev
subjects:
- kind: User
  name: user-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: creator
  apiGroup: rbac.authorization.k8s.io
