kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: creator
rules:
- apiGroups: [""]
  resources: ["pods, deployments, services"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]